name: Bump Version
run-name: Bump Version
on: [push]
permissions:
    contents: write
    
jobs:
    Bump-Version:
        name: Bump Version
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                node-version: [20.x]
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Bump Version
              with:
                  target-branch: master
                  skip-tag: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              id: bump_version
              uses: phips28/gh-action-bump-version@master

